### ISSUE TITLE
Update for v4.0

### ISSUE THREAD

**Issue by fijijavis** [webdriverio/sublime-bundle#1]
How would I update this package to work with the v4.0 version of WDIO?

Thanks

**Comment by christian-bromann** [comment]
Clone the project, install dependencies and run `npm run generate-snippets` should do the trick. I haven't got a chance to do that yet sorry, but will try to get this out soon!

**Comment by fijijavis** [comment]
No worries.  I updated package.json dependencies for webdriverio to "^4.0.0" then followed your steps.  Looks good now.  If that's all then I could submit a pull request.

Thanks

**Comment by fijijavis** [comment]
Do you think you could publish a new version of this to Package Control?
